In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
weather_df = pd.read_excel("weather.xlsx")

In [5]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [ ]:
# head method returns the first 5 rows of the dataframe by default. You can also specify the number of rows to return by passing an integer as an argument to the head method. For example, weather_df.head(10) will return the first 10 rows of the dataframe.
weather_df.head()

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [ ]:
# tail method returns the last 5 rows of the dataframe by default. You can also specify the number of rows to return by passing an integer as an argument to the tail method. For example, weather_df.tail(10) will return the last 10 rows of the dataframe.
weather_df.tail()

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [ ]:
# info method prints a summary of the dataframe, including the number of non-null values, the data types of each column, and the memory usage of the dataframe.
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [ ]:
# describe method generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset’s distribution, excluding NaN values. It provides information such as count, mean, standard deviation, minimum, maximum, and quartile values for each numerical column in the dataframe.
weather_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [ ]:
# count method returns the number of non-null values in each column of the dataframe. It can be useful for identifying missing data in the dataframe.
weather_df.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [ ]:
# isna method returns a dataframe of the same shape as the original dataframe, but with boolean values indicating whether each element is missing (NaN) or not. It can be useful for identifying missing data in the dataframe.
weather_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False