In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
weather_df = pd.read_excel("weather.xlsx")

In [4]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [5]:
# head method returns the first 5 rows of the dataframe by default. You can also specify the number of rows to return by passing an integer as an argument to the head method. For example, weather_df.head(10) will return the first 10 rows of the dataframe.
weather_df.head()

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [6]:
# tail method returns the last 5 rows of the dataframe by default. You can also specify the number of rows to return by passing an integer as an argument to the tail method. For example, weather_df.tail(10) will return the last 10 rows of the dataframe.
weather_df.tail()

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [7]:
# info method prints a summary of the dataframe, including the number of non-null values, the data types of each column, and the memory usage of the dataframe.
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [8]:
# describe method generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset’s distribution, excluding NaN values. It provides information such as count, mean, standard deviation, minimum, maximum, and quartile values for each numerical column in the dataframe.
weather_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [9]:
# count method returns the number of non-null values in each column of the dataframe. It can be useful for identifying missing data in the dataframe.
weather_df.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [10]:
# isna method returns a dataframe of the same shape as the original dataframe, but with boolean values indicating whether each element is missing (NaN) or not. It can be useful for identifying missing data in the dataframe.
weather_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

In [12]:
weather_na_df = pd.read_excel("weatherna.xlsx")

In [13]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [14]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [15]:
weather_na_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [18]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [ ]:
# dropna method removes any rows that contain missing values (NaN) from the dataframe. It can be useful for cleaning the dataframe and preparing it for analysis.
weather_na_df.dropna()

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [20]:
weather_na_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
# fillna method fills the missing values (NaN) in the dataframe with a specified value. It can be useful for handling missing data in the dataframe and preparing it for analysis.
weather_na_df.fillna(20)

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0       20.0   14.0
2      20.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0      20.0       22.0   20.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0   20.0
8      22.0      16.0       16.0   20.0

In [22]:
weather_na_df.mean()

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [23]:
weather_na_df.median()

Istanbul     21.5
New York     13.5
Amsterdam    15.5
Paris        15.0
dtype: float64

In [24]:
weather_na_df.fillna(weather_na_df.mean())

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

In [25]:
weather_na_df.max()

Istanbul     28.0
New York     16.0
Amsterdam    22.0
Paris        20.0
dtype: float64

In [26]:
weather_na_df.min()

Istanbul     15.0
New York     10.0
Amsterdam    14.0
Paris        12.0
dtype: float64