In [1]:
import numpy as np
import pandas as pd

In [2]:
grades = {"Alice": 50, "James": 60, "Lars": 30}

In [3]:
pd.Series(grades)

Alice    50
James    60
Lars     30
dtype: int64

Data Frame

In [4]:
data = np.random.rand(4, 3)

In [5]:
data

array([[0.44399926, 0.83317692, 0.63128938],
       [0.15518991, 0.10643258, 0.89428416],
       [0.50260503, 0.67237586, 0.46199673],
       [0.16169555, 0.33353476, 0.8671407 ]])

In [6]:
data_frame = pd.DataFrame(data)

In [7]:
data_frame

          0         1         2
0  0.443999  0.833177  0.631289
1  0.155190  0.106433  0.894284
2  0.502605  0.672376  0.461997
3  0.161696  0.333535  0.867141

In [8]:
new_df = pd.DataFrame(data, columns=["Column 1", "Column 2", "Column 3"], index=["Row 1", "Row 2", "Row 3", "Row 4"])

In [9]:
new_df

       Column 1  Column 2  Column 3
Row 1  0.443999  0.833177  0.631289
Row 2  0.155190  0.106433  0.894284
Row 3  0.502605  0.672376  0.461997
Row 4  0.161696  0.333535  0.867141

In [10]:
new_df["Extra"] = 10

In [11]:
new_df

       Column 1  Column 2  Column 3  Extra
Row 1  0.443999  0.833177  0.631289     10
Row 2  0.155190  0.106433  0.894284     10
Row 3  0.502605  0.672376  0.461997     10
Row 4  0.161696  0.333535  0.867141     10

In [12]:
# axis=0 specifies that operations will be performed along rows, axis=1 specifies that operations will be performed along columns.
new_df.drop("Extra", axis=1)

       Column 1  Column 2  Column 3
Row 1  0.443999  0.833177  0.631289
Row 2  0.155190  0.106433  0.894284
Row 3  0.502605  0.672376  0.461997
Row 4  0.161696  0.333535  0.867141

In [13]:
new_df

       Column 1  Column 2  Column 3  Extra
Row 1  0.443999  0.833177  0.631289     10
Row 2  0.155190  0.106433  0.894284     10
Row 3  0.502605  0.672376  0.461997     10
Row 4  0.161696  0.333535  0.867141     10

In [14]:
new_df.drop("Extra", axis=1, inplace=True)

In [15]:
new_df

       Column 1  Column 2  Column 3
Row 1  0.443999  0.833177  0.631289
Row 2  0.155190  0.106433  0.894284
Row 3  0.502605  0.672376  0.461997
Row 4  0.161696  0.333535  0.867141

In [16]:
new_df.loc["Row 1"]

Column 1    0.443999
Column 2    0.833177
Column 3    0.631289
Name: Row 1, dtype: float64

In [17]:
new_df.loc["Row 1"]["Column 2"]

np.float64(0.8331769246489367)

In [19]:
reset_frame = new_df.reset_index()

In [20]:
reset_frame

   index  Column 1  Column 2  Column 3
0  Row 1  0.443999  0.833177  0.631289
1  Row 2  0.155190  0.106433  0.894284
2  Row 3  0.502605  0.672376  0.461997
3  Row 4  0.161696  0.333535  0.867141

Multi Index

In [21]:
first_index = ["Simpson", "Simpson", "Simpson", "South Park", "South Park", "South Park"]

In [22]:
innder_index = ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [23]:
zipped_index = list(zip(first_index, innder_index))

In [24]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [25]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [27]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [28]:
sample_values = np.ones((6, 2))

In [29]:
multi_index_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Salary", "Seniority"])

In [30]:
multi_index_df

                    Salary  Seniority
Simpson    Homer       1.0        1.0
           Bart        1.0        1.0
           Marge       1.0        1.0
South Park Cartman     1.0        1.0
           Kenny       1.0        1.0
           Kyle        1.0        1.0

In [ ]:
multi_index_df.loc["Simpson"]

       Salary  Seniority
Homer     1.0        1.0
Bart      1.0        1.0
Marge     1.0        1.0

In [32]:
multi_index_df.loc["Simpson"].loc["Homer"]

Salary       1.0
Seniority    1.0
Name: Homer, dtype: float64