In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

set1no = 900
set2no = 100

df1 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0, scale=1, size=set1no),
    "feature_2": np.random.normal(loc=0, scale=1, size=set1no),
    "target": [0] * set1no
})

df2 = pd.DataFrame({
    "feature_1": np.random.normal(loc=0, scale=1, size=set2no),
    "feature_2": np.random.normal(loc=0, scale=1, size=set2no),
    "target": [1] * set2no
})

In [3]:
df1.head()

   feature_1  feature_2  target
0   0.496714   0.368673       0
1  -0.138264  -0.393339       0
2   0.647689   0.028745       0
3   1.523030   1.278452       0
4  -0.234153   0.191099       0

In [4]:
df2.head()

   feature_1  feature_2  target
0   1.901191   0.696954       1
1  -0.060661  -0.333819       1
2  -0.708407   1.173125       1
3  -1.513714   0.369642       1
4  -1.803140  -0.107302       1

In [5]:
df = pd.concat([df1, df2]).reset_index(drop=True)

In [6]:
df

     feature_1  feature_2  target
0     0.496714   0.368673       0
1    -0.138264  -0.393339       0
2     0.647689   0.028745       0
3     1.523030   1.278452       0
4    -0.234153   0.191099       0
..         ...        ...     ...
995  -0.370011   1.070150       1
996  -0.258796  -0.026521       1
997   1.598647  -0.881875       1
998   0.560919  -0.163067       1
999  -0.295480  -0.744903       1

[1000 rows x 3 columns]

In [7]:
df["target"].unique()

array([0, 1])

In [8]:
df["target"].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [10]:
# There are two approaches to making this unbalanced data set balanced.

# upsampling --> upsample minority
# downsampling --> downsample majority

Upsampling Example

In [11]:
df_minority = df[df["target"] == 1]

In [12]:
df_minority

     feature_1  feature_2  target
900   1.901191   0.696954       1
901  -0.060661  -0.333819       1
902  -0.708407   1.173125       1
903  -1.513714   0.369642       1
904  -1.803140  -0.107302       1
..         ...        ...     ...
995  -0.370011   1.070150       1
996  -0.258796  -0.026521       1
997   1.598647  -0.881875       1
998   0.560919  -0.163067       1
999  -0.295480  -0.744903       1

[100 rows x 3 columns]

In [13]:
df_majority = df[df["target"] == 0]

In [14]:
df_majority

     feature_1  feature_2  target
0     0.496714   0.368673       0
1    -0.138264  -0.393339       0
2     0.647689   0.028745       0
3     1.523030   1.278452       0
4    -0.234153   0.191099       0
..         ...        ...     ...
895   0.648710  -0.751969       0
896  -0.167118  -0.319054       0
897   0.146714  -0.796026       0
898   1.206509   1.076007       0
899  -0.816936   0.021312       0

[900 rows x 3 columns]

In [15]:
from sklearn.utils import resample

In [17]:
df_minority_upsampled = resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42)

In [18]:
df_minority_upsampled

     feature_1  feature_2  target
951   1.775311   1.261922       1
992  -0.436386   1.188913       1
914  -0.268531  -1.801058       1
971  -0.214921  -2.940389       1
960  -0.134309  -0.054894       1
..         ...        ...     ...
952  -1.193637  -0.905732       1
965  -1.662492   0.089581       1
976  -0.562168   1.124113       1
942  -0.548725   0.269127       1
974   1.310309  -0.018709       1

[900 rows x 3 columns]

In [21]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [23]:
df_upsampled["target"].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [25]:
df_majority_downsampled = resample(df_majority, replace=True, n_samples=len(df_minority), random_state=42)

In [27]:
df_majority_downsampled["target"].value_counts()

target
0    100
Name: count, dtype: int64

In [28]:
df_downsampled = pd.concat([df_majority_downsampled, df_minority])

In [30]:
df_downsampled["target"].value_counts()

target
0    100
1    100
Name: count, dtype: int64